# Despite having these configured in DNS, I _must_ use the IP address in the
# host field here for broadlink_send_packet in scripts to work correctly.
- platform: broadlink
  host: 192.168.1.232
  mac: '24:df:a7:7a:80:da'
  timeout: 15

- platform: template
  switches:
    lounge_tv:
      friendly_name: 'Lounge TV'
      value_template: "{{ is_state('device_tracker.lounge_tv', 'home') }}"
      turn_on:
        service: script.lounge_tv_on
        data:
          entity_id: script.lounge_tv_on
      turn_off:
        service: script.lounge_tv_off
        data:
          entity_id: script.lounge_tv_off
      icon_template: >-
        {% if is_state('device_tracker.lounge_tv', 'home') %}
          mdi:television
        {% else %}
          mdi:television-off
        {% endif %}

