# Despite having these configured in DNS, I _must_ use the IP address in the
# host field here for broadlink_send_packet in scripts to work correctly.
- platform: broadlink
  host: 192.168.1.230
  mac: '34:ea:34:41:43:32'
  timeout: 15

- platform: template
  switches:
    office_chromecast:
      friendly_name: 'Office Chromecast'
      value_template: "{{ is_state('device_tracker.office_chromecast', 'home') }}"
      turn_on:
        service: script.office_chromecast_on
        data:
          entity_id: script.office_chromecast_on
      turn_off:
        service: script.office_chromecast_off
        data:
          entity_id: script.office_chromecast_off
      icon_template: >-
        {% if is_state('device_tracker.office_chromecast', 'home') %}
          mdi:television
        {% else %}
          mdi:television-off
        {% endif %}
    office_bluray:
      friendly_name: 'Office Bluray'
      value_template: "{{ is_state('device_tracker.office_bluray', 'home') }}"
      turn_on:
        service: script.office_bluray_on
        data:
          entity_id: script.office_bluray_on
      turn_off:
        service: script.office_bluray_off
        data:
          entity_id: script.office_bluray_off
      icon_template: >-
        {% if is_state('device_tracker.office_bluray', 'home') %}
          mdi:television
        {% else %}
          mdi:television-off
        {% endif %}
