# Brilliant Wifi Smart PLug running Tasmota. Controls the office water cooler.
- platform: mqtt
  name: "Office water cooler"
  command_topic: "cmnd/sonoff8/POWER1"

# Brilliant Wifi Smart PLug running Tasmota. Controls the heated towel rail in the master ensuite.
- platform: mqtt
  name: "Ensuite towel rail"
  command_topic: "cmnd/sonoff11/POWER1"
