- platform: command_line
  switches:
    watering_for_yurt:
      friendly_name: Watering for yurt
      command_on: /srv/homeassistant/config/helpers/yurtcmd yurt1.home.stillhq.com 1 on
      command_off: /srv/homeassistant/config/helpers/yurtcmd yurt1.home.stillhq.com 1 off
  
    watering_for_fern:
      friendly_name: Watering for fern
      command_on: /srv/homeassistant/config/helpers/yurtcmd yurt1.home.stillhq.com 2 on
      command_off: /srv/homeassistant/config/helpers/yurtcmd yurt1.home.stillhq.com 2 off
  
    watering_for_shade_garden:
      friendly_name: Watering for shade garden
      command_on: /srv/homeassistant/config/helpers/yurtcmd yurt1.home.stillhq.com 3 on
      command_off: /srv/homeassistant/config/helpers/yurtcmd yurt1.home.stillhq.com 3 off

    watering_for_front_door:
      friendly_name: Watering for front door
      command_on: /srv/homeassistant/config/helpers/yurtcmd yurt2.home.stillhq.com 1 on
      command_off: /srv/homeassistant/config/helpers/yurtcmd yurt2.home.stillhq.com 1 off

    watering_for_back_fence:
      friendly_name: Watering for back fence
      command_on: /srv/homeassistant/config/helpers/yurtcmd yurt3.home.stillhq.com 1 on
      command_off: /srv/homeassistant/config/helpers/yurtcmd yurt3.home.stillhq.com 1 off
