# Yurt wifi relay board controlling watering near the fern garden
- platform: mqtt
  name: "Watering for ferns"
  command_topic: "cmnd/yurt1/POWER1"
  state_topic: "tele/yurt1/POWER1"
  state_on: "True"
  state_off: "False"
  payload_on: "True"
  payload_off: "False"
  
- platform: mqtt
  name: "Watering for yurt"
  command_topic: "cmnd/yurt1/POWER2"
  state_topic: "tele/yurt1/POWER2"
  state_on: "True"
  state_off: "False"
  payload_on: "True"
  payload_off: "False"
  
- platform: mqtt
  name: "Watering for veges"
  command_topic: "cmnd/yurt1/POWER3"
  state_topic: "tele/yurt1/POWER3"
  state_on: "True"
  state_off: "False"
  payload_on: "True"
  payload_off: "False"
