--- # Install the mqttexporter
- hosts: localhost
  become: yes
  become_method: sudo
  gather_facts: yes
  connection: ssh
  tasks:
  - include: python_modern_pip.yml

  - name: install paho
    pip:
      name: paho-mqtt

  - name: copy mqtt2yurt service configuration
    copy:
      src: "mqtt2yurt.service"
      dest: "/etc/systemd/system/mqtt2yurt.service"
      owner: root
      group: root
      mode: 0444
  - name: systemctl enable mqtt2yurt
    service:
      name: mqtt2yurt
      enabled: yes
      state: restarted