#!/usr/bin/python3

import datetime
import socket
import sys
import time

COMMANDS = {
    'software_version': 'Z',
    'relay_states': '[',
    'dc_input_voltage': ']',
    'temperature_as_raw': 'a',
    'temperature_as_string': 'b',
    'relay_all_on': 'd',
    'relay_1_on': 'e',
    'relay_2_on': 'f',
    'relay_3_on': 'g',
    'relay_4_on': 'h',
    'relay_all_off': 'n',
    'relay_1_off': 'o',
    'relay_2_off': 'p',
    'relay_3_off': 'q',
    'relay_4_off': 'r'
}


def sendcommand(hostname, command):
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((hostname, 2000))
    s.settimeout(1)
    s.recv(1024)
    s.send(command.encode('ascii'))

    try:
        return s.recv(1024).rstrip()
    except socket.timeout:
        return None


f = open('/srv/homeassistant/config/helpers/yurtcmd.log', 'a')
f.write('----- %s %s -----\n' %(datetime.datetime.now(), sys.argv))

for i in range(10):
    try:
        hostname = sys.argv[1]
        relay = sys.argv[2]

        if relay == 'temp':
            print(sendcommand(hostname, COMMANDS['temperature_as_string']))
        else:
            command = sys.argv[3]
            f.write('Sending yurt command: %s to %s\n' %(COMMANDS['relay_%s_%s' %(relay, command)], hostname))
            sendcommand(hostname, COMMANDS['relay_%s_%s' %(relay, command)])

        f.write('Yurt command successful.\n')
        break

    except Exception as e:
        f.write('%s\n' % e)
        f.write('  ...\n')
        time.sleep(5)

f.close()
