homeassistant:
  name: 33FL
  country: AU
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 594
  unit_system: metric
  time_zone: Australia/Canberra
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret api_password

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Enable ffmpeg
ffmpeg:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.3

logger:
  default: info

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
#map:

# Enable sun tracking
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    language: 'en-uk'
    cache_dir: /tmp/tts

# Cloud
cloud:

owntracks:

automation: !include_dir_merge_list automation
device_tracker: !include device_tracker.yaml
group: !include groups.yaml
script: !include_dir_merge_named scripts/
binary_sensor: !include binary_sensors.yaml
shell_command: !include shell_commands.yaml

recorder:
  purge_keep_days: 7

system_health:
mobile_app:

zha:
  custom_quirks_path: /srv/homeassistant/config/custom_zha_quirks/

command_line: !include command_line.yaml

mqtt:
  - sensor: !include mqtt/sensors.yaml
  - light: !include mqtt/lights.yaml

template:
  - sensor:
      # Are we on the summer or winter watering schedule? Summer is defined
      # by law in this case to be September thru May. Given how cold it is
      # at the start of May (freezing overnight), I am going to assume they mean
      # restrictions end at the start of May.
      - name: Watering restrictions apply
        state: >-
          {% if now().month in [9, 10, 11, 12, 1, 2, 3] -%}
            on
          {%- else -%}
            off
          {%- endif %}

# My custom components
# bom_forecast:
# event_history:
# holidays:
