homeassistant:
  name: 33FL
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 594
  unit_system: metric
  time_zone: Australia/Canberra
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Enable ffmpeg
ffmpeg:

http:
  base_url: !secret base_url
  api_password: !secret api_password

logger:
  default: warning
  logs:
          roomba: warning

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
#map:

# Enable sun tracking
sun:

# BOM weather forecasts
weather:
- platform: bom
  station: IDN60903.94925

# Text to speech
tts:
  - platform: google
    cache: true
    language: 'en-uk'
    cache_dir: /tmp/tts

# Cloud
cloud:

owntracks:

mqtt:
  broker: !secret mqtt_broker

automation: !include_dir_merge_list automation
camera: !include cameras.yaml
device_tracker: !include device_tracker.yaml
group: !include groups.yaml
light: !include light.yaml
script: !include_dir_merge_named scripts
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
vacuum: !include vacuum.yaml

vera:
  vera_controller_url: !secret vera_controller

media_player:
  - platform: samsungtv
    host: loungetv.home.stillhq.com
    name: Lounge Display
    mac: 5c:f6:dc:b1:a9:98

  - platform: plex
    entity_namespace: 'plex'
    ip_address: 192.168.1.6
    port: 32400
    token: !secret plex_token
    ssl: true
    verify: false

notify:
  - name: slack
    platform: slack
    api_key: !secret slack_api_key
    default_channel: '#house'

recorder:
  purge_interval: 1
  purge_keep_days: 7

# My custom components
bom_forecast:
event_history:
holidays:
