# This is the new sm2135 based version of the Genio RGBW light. It requires this template:
# {"NAME":"MiraBellaGenio","GPIO":[0,0,0,0,0,0,0,0,181,0,180,0,0],"FLAG":0,"BASE":18}
# And you need to send a SetOption37 31 for colours to be correct.
- platform: mqtt
  name: "Master Bed Catherine"
  command_topic: "cmnd/sonoff10/POWER"
  state_topic: "tele/sonoff10/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/sonoff10/LWT"
  brightness_command_topic: "cmnd/sonoff10/Dimmer"
  brightness_state_topic: "tele/sonoff10/STATE"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  rgb_command_topic: "cmnd/sonoff10/Color2"
  rgb_state_topic: "tele/sonoff10/STATE"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  effect_command_topic: "cmnd/sonoff10/Scheme"
  effect_state_topic: "tele/sonoff10/STATE"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

# This is the new sm2135 based version of the Genio RGBW light. It requires this template:
# {"NAME":"MiraBellaGenio","GPIO":[0,0,0,0,0,0,0,0,181,0,180,0,0],"FLAG":0,"BASE":18}
# And you need to send a SetOption37 31 for colours to be correct.
- platform: mqtt
  name: "Master Bed Michael"
  command_topic: "cmnd/sonoff16/POWER"
  state_topic: "tele/sonoff16/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/sonoff16/LWT"
  brightness_command_topic: "cmnd/sonoff16/Dimmer"
  brightness_state_topic: "tele/sonoff16/STATE"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  rgb_command_topic: "cmnd/sonoff16/Color2"
  rgb_state_topic: "tele/sonoff16/STATE"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  effect_command_topic: "cmnd/sonoff16/Scheme"
  effect_state_topic: "tele/sonoff16/STATE"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

# RGB Mirabella Genio running Tasmota
# Remember to run "SetOption17 1" and "SetOption59 1" on the web console before deployment!
# See https://github.com/arendst/Sonoff-Tasmota/wiki/Home-Assistant-%E2%80%90-Manual-Config#rgb-lights for details.
- platform: mqtt
  name: "Jacqui lamp"
  command_topic: "cmnd/sonoff12/POWER"
  state_topic: "tele/sonoff12/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/sonoff12/LWT"
  brightness_command_topic: "cmnd/sonoff12/Dimmer"
  brightness_state_topic: "tele/sonoff12/STATE"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  rgb_command_topic: "cmnd/sonoff12/Color2"
  rgb_state_topic: "tele/sonoff12/STATE"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  effect_command_topic: "cmnd/sonoff12/Scheme"
  effect_state_topic: "tele/sonoff12/STATE"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

# Arlec fairy lights on the back deck
- platform: mqtt
  name: "Back deck 1"
  command_topic: "cmnd/sonoff14/POWER"
  state_topic: "tele/sonoff14/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/sonoff14/LWT"
  effect_command_topic: "cmnd/sonoff14/Event"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "Back deck 2"
  command_topic: "cmnd/sonoff15/POWER"
  state_topic: "tele/sonoff15/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/sonoff15/LWT"
  effect_command_topic: "cmnd/sonoff15/Event"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false
