title: 33FL
views:
  - title: Office
    cards:
    - type: entity-button
      entity: script.office_chromecast_on
      icon: 'mdi:television'
      tap_action:
        action: call-service
        service: script.turn_on
        service_data:
          entity_id: script.office_chromecast_on
    - type: entity-button
      entity: script.office_bluray_on
      icon: 'mdi:television'
      tap_action:
        action: call-service
        service: script.turn_on
        service_data:
          entity_id: script.office_bluray_on
