- alias: 'Lab too warm'
  trigger:
    - platform: numeric_state
      entity_id: sensor.lab_temperature
      above: 26.0
      for: '00:01:00'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: switch.sun_room_ac
      state: 'off'
  action:
    - service: script.turn_on
      entity_id: script.lab_cooling_on

- alias: 'Lab failed to cool'
  trigger:
    - platform: numeric_state
      entity_id: sensor.lab_temperature
      above: 28.0
      for: '00:15:00'
  action:
    - service: switch.turn_off
      entity_id: switch.sun_room_ac
    - delay: '00:00:20'
    - service: script.turn_on
      entity_id: script.lab_cooling_on
    - service: notify.slack
      data_template:
        message: 'We are failing to keep the lab cool.'

- alias: 'Lab now cool'
  trigger:
    - platform: numeric_state
      entity_id: sensor.lab_temperature
      below: 24.0
      for: '00:05:00'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: switch.sun_room_ac
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.sun_room_ac

- alias: 'Lab cooling summary'
  trigger:
    - platform: time
      at: '23:55:00'
  action:
    - service: notify.slack
      data_template:
        message: 'We used {{state_attr("switch.sun_room_ac", "today_energy_kwh")}} kwh of electricty cooling the lab today.'
