- alias: 'Office power up'
  hide_entity: false
  trigger:
    - platform: state
      entity_id: sensor.coffee_maker
      from: 'idle'
      to: 'brewing'
  condition:
    condition: and
    conditions:
    - condition: time
      after: '04:00:00'
      before: '10:00:00'
    - condition: state
      entity_id: device_tracker.michael_summary
      state: 'home'
    - condition: template
      value_template: '{{ (as_timestamp(now()) - states.event_history.events.attributes.good_morning | default(0) | int > 64800 )}}'
  action:
    - service: notify.slack
      data_template:
        message: 'Good morning! Today is forecast to be "{{states.bom_forecast.forecast.attributes.today_forecast}}", with a maximum of {{states.bom_forecast.forecast.attributes.today_temp_max}} and {{states.bom_forecast.forecast.attributes.today_rain}} chance of rain.'
    - service: event_history.record_event
      data:
        name: 'good_morning'
    - service: light.turn_on
      entity_id: light.office_desk
    - service: vacuum.turn_on
      data:
        entity_id: vacuum.claude_von_roomba
    - service: notify.slack
      data:
        message: 'I have turned on the lights in the office and set the AC to just fan. You are welcome.'

#- alias: 'Office power down'
#  hide_entity: false
#  trigger:
#    
#  action:
#    - service: light.turn_off
#      entity_id: light.office_desk
#    - service: light.turn_off
#      entity_id: light.office_lights_4
#    - service: script.office_aircon_power_off
