- alias: 'Publish presence'
  trigger:
  - platform: time_pattern
    minutes: '/2'
  action:
  - service: mqtt.publish
    data_template:
      topic: 'homeassistant/presence/michael_phone'
      payload_template: '{{ states.device_tracker.michaels_phone.state }}'
  - service: mqtt.publish
    data_template:
      topic: 'homeassistant/presence/michael_atom'
      payload_template: '{{ states.device_tracker.michaels_atom.state }}'
  - service: mqtt.publish
    data_template:
      topic: 'homeassistant/presence/michael_running_keys'
      payload_template: '{{ states.device_tracker.michaels_running_keys.state }}'
  - service: mqtt.publish
    data_template:
      topic: 'homeassistant/presence/catherine'
      payload_template: '{{ states.device_tracker.catherines_phone.state }}'
  - service: mqtt.publish
    data_template:
      topic: 'homeassistant/presence/andrew'
      payload_template: '{{ states.device_tracker.andrews_phone.state }}'
  - service: mqtt.publish
    data_template:
      topic: 'homeassistant/presence/matthew'
      payload_template: '{{ states.device_tracker.matthews_phone.state }}'
