- alias: 'Evening indoor regardless of who is home'
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:30:00"
  action:
    - service: light.turn_on
      entity_id: [light.aj_lamp_level_light_color_on_off, light.matt_lamp_level_light_color_on_off, light.office_couch_left_2, light.office_couch_right_2, light.lounge_left_3, light.lounge_right_3, light.hall_2, light.hall_3, light.kitchen_sink, light.master_ceiling_1, light.master_ceiling_4, light.aj_ceiling]
      data:
        brightness: 255
        rgb_color: [255, 145, 145]

- alias: 'Evening indoor Jacqui special case'
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:30:00"
  condition: and
  conditions:
    - condition: state
      entity_id: light.jacqui_lamp
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.jacqui_lamp
      data:
        brightness: 255
        rgb_color: [255, 145, 145]

- alias: 'Jacqui bed time'
  trigger:
    - platform: time
      at: "19:00:00"
  action:
    - service: light.turn_on
      entity_id: light.jacqui_lamp
      data:
        brightness: 69
        rgb_color: [255, 0, 0]

- alias: 'Evening outdoor regardless of who is home'
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:10:00"
  action:
    - service: light.turn_on
      entity_id: [light.hue_ambiance_downlight_1, light.hue_ambiance_downlight_2]
      data:
        brightness: 50
    - service: light.turn_on
      entity_id: [light.back_deck_1, light.back_deck_2]
      data:
        effect: 7

- alias: 'Morning outfoor regarless of who is home'
  trigger:
    - platform: sun
      event: sunrise
      offset: "+00:10:00"
  action:
    - service: light.turn_off
      entity_id: [light.hue_ambiance_downlight_1, light.hue_ambiance_downlight_2]
    - service: light.turn_off
      entity_id: [light.back_deck_1, light.back_deck_2]
