- alias: 'Evening indoor regardless of who is home'
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:30:00"
  action:
    - service: script.sunset_lights
      data: {}

- alias: 'Evening indoor Jacqui special case'
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:30:00"
  action:
    - service: light.turn_on
      entity_id: light.jacqui_lamp
      data:
        brightness: 255
        rgb_color: [255, 255, 255]

- alias: 'Morning indoor Jacqui special case'
  trigger:
    - platform: time
      at: "06:00:00"
  action:
    - service: light.turn_on
      entity_id: light.jacqui_lamp
      data:
        brightness: 10
        rgb_color: [0, 33, 0]

- alias: 'Morning final Jacqui special case'
  trigger:
    - platform: time
      at: "10:00:00"
  action:
    - service: light.turn_off
      entity_id: light.jacqui_lamp

- alias: 'Evening outdoor regardless of who is home'
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:10:00"
  action:
    - service: light.turn_on
      entity_id: [light.hue_ambiance_downlight_1, light.hue_ambiance_downlight_2]
      data:
        brightness: 50
    - service: light.turn_on
      entity_id: [light.back_deck_1, light.back_deck_2]
      data:
        effect: 7

- alias: 'Morning outfoor regardless of who is home'
  trigger:
    - platform: sun
      event: sunrise
      offset: "+00:10:00"
  action:
    - service: light.turn_off
      entity_id: [light.hue_ambiance_downlight_1, light.hue_ambiance_downlight_2]
    - service: light.turn_off
      entity_id: [light.back_deck_1, light.back_deck_2]
