# Local law requires watering at night between September and May. That said,
# we need to mist the fern frequently for short periods when its hot or it
# will die.

##### Shade garden #####

- alias: 'Water the shade garden (winter)'
  trigger:
    platform: time
    at: '12:00:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - sun
          - wed
      - condition: state
        entity_id: 'sensor.watering_restrictions_apply'
        state: 'off'
  action:
    - service: script.turn_on
      entity_id: script.shade_garden_watering

- alias: 'Water the shade garden (summer)'
  trigger:
    platform: time
    at: '20:00:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - sun
          - wed
      - condition: state
        entity_id: 'sensor.watering_restrictions_apply'
        state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.shade_garden_watering

- alias: 'Water the shade garden (more in summer)'
  trigger:
    platform: time
    at: '20:00:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - thu
          - fri
          - sat
      - condition: numeric_state
        entity_id: sensor.outside_temperature
        above: 25.0
      - condition: state
        entity_id: 'sensor.watering_restrictions_apply'
        state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.warm_weather_shade_garden_watering

##### Fern #####

- alias: 'Water the fern more when its hot (8am)'
  trigger:
    platform: time
    at: '08:00:00'
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.outside_temperature
      above: 20.0
  action:
    - service: script.turn_on
      entity_id: script.warm_weather_fern_watering

- alias: 'Water the fern more when its hot (noon)'
  trigger:
    platform: time
    at: '12:00:00'
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.outside_temperature
      above: 25.0
    - condition: time
      weekday:
        - mon
        - tue
        - thu
        - fri
        - sat
  action:
    - service: script.turn_on
      entity_id: script.warm_weather_fern_watering

- alias: 'Water the fern more when its hot (4pm)'
  trigger:
    platform: time
    at: '16:00:00'
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.outside_temperature
      above: 25.0
  action:
    - service: script.turn_on
      entity_id: script.warm_weather_fern_watering

##### Front door #####

- alias: 'Water the garden by the front door (winter)'
  trigger:
    platform: time
    at: '11:00:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - sun
          - wed
      - condition: state
        entity_id: 'sensor.watering_restrictions_apply'
        state: 'off'
  action:
    - service: script.turn_on
      entity_id: script.front_door_watering

- alias: 'Water the garden by the front door (summer)'
  trigger:
    platform: time
    at: '7:30:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - sun
          - wed
      - condition: state
        entity_id: 'sensor.watering_restrictions_apply'
        state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.front_door_watering

- alias: 'Water the garden by the front door (more in summer)'
  trigger:
    platform: time
    at: '19:30:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
          - sat
          - sun
      - condition: numeric_state
        entity_id: sensor.outside_temperature
        above: 25.0
      - condition: state
        entity_id: 'sensor.watering_restrictions_apply'
        state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.warm_weather_front_door_watering

##### Back fence #####

- alias: 'Water the garden by back fence (winter)'
  trigger:
    platform: time
    at: '13:00:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - sun
          - wed
      - condition: state
        entity_id: 'sensor.watering_restrictions_apply'
        state: 'off'
  action:
    - service: script.turn_on
      entity_id: script.back_fence_watering

- alias: 'Water the garden by the back fence (summer mornings)'
  trigger:
    platform: time
    at: '7:45:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'sensor.watering_restrictions_apply'
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.outside_temperature
        above: 15.0
  action:
    - service: script.turn_on
      entity_id: script.back_fence_watering

- alias: 'Water the garden by the back fence (summer evenings)'
  trigger:
    platform: time
    at: '19:45:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'sensor.watering_restrictions_apply'
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.outside_temperature
        above: 20.0
  action:
    - service: script.turn_on
      entity_id: script.back_fence_watering
