- alias: Ensure all watering off on startup
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: switch.turn_off
      entity_id: switch.watering_for_fern
    - service: switch.turn_off
      entity_id: switch.watering_for_shade_garden
    - service: switch.turn_off
      entity_id: switch.watering_for_yurt

- alias: Water fern for ten minutes at 3pm
  trigger:
    platform: time
    hours: 15
    minutes: 0
    seconds: 0
  action:
    - service: switch.turn_on
      entity_id: switch.watering_for_fern
    - delay: 0:05:00
    - service: switch.turn_off
      entity_id: switch.watering_for_fern
    - delay: 0:01:00
    - service: switch.turn_off
      entity_id: switch.watering_for_fern
    - delay: 0:01:00
    - service: switch.turn_off
      entity_id: switch.watering_for_fern
    - delay: 0:01:00
    - service: switch.turn_off
      entity_id: switch.watering_for_fern

- alias: Water shade garden for ten minutes at 3pm
  trigger:
    platform: time
    hours: 15
    minutes: 0
    seconds: 0
  action:
    - service: switch.turn_on
      entity_id: switch.watering_for_shade_garden
    - delay: 0:05:00
    - service: switch.turn_off
      entity_id: switch.watering_for_shade_garden
    - delay: 0:01:00
    - service: switch.turn_off
      entity_id: switch.watering_for_shade_garden
    - delay: 0:01:00
    - service: switch.turn_off
      entity_id: switch.watering_for_shade_garden
    - delay: 0:01:00
    - service: switch.turn_off
      entity_id: switch.watering_for_shade_garden