- alias: 'Office power down'
  hide_entity: false
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: office_shutdown
  action:
    - service: light.turn_off
      entity_id: light.office_desk
    - service: light.turn_off
      entity_id: light.office_couch_left
    - service: light.turn_off
      entity_id: light.office_couch_right
    - service: light.turn_off
      entity_id: light.office_lights_4
    - service: script.office_aircon_power_off
    - service: switch.turn_off
      entity_id: switch.office_workbench
    - service: switch.turn_off
      entity_id: switch.office_desk_optional

- alias: 'Office chromecast on'
  hide_entity: false
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: office_chromecast_on
  action:
    - service: script.office_chromecast_on

- alias: 'Office chromecast off'
  hide_entity: false
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: office_chromecast_off
  action:
    - service: script.office_chromecast_off
