- id: office_power_down
  alias: 'Office power down'
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: office_shutdown
  action:
    - service: light.turn_off
      entity_id: [light.office_desk, light.office_couch_left, light.office_couch_right, light.office_lights_4]
    - service: script.office_aircon_power_off
    - service: script.office_tv_power_off
    - service: switch.turn_off
      entity_id: switch.office_workbench
    - service: switch.turn_off
      entity_id: switch.office_desk_optional
    - delay: '00:10:00'
    - service: light.turn_off
      entity_id: [light.back_deck_1, light.back_deck_2]

- alias: 'Office chromecast on'
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: office_chromecast_on
  action:
    - service: script.office_chromecast_on

- alias: 'Office chromecast off'
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: office_chromecast_off
  action:
    - service: script.office_chromecast_off

- id: outside_power_down
  alias: 'We are all inside'
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: outside_shutdown
  action:
    - service: light.turn_off
      entity_id: [light.back_deck_1, light.back_deck_2]
    - service: light.turn_off
      entity_id: [light.hue_ambiance_downlight_1, light.hue_ambiance_downlight_2]

- alias: 'We are all in bed'
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: inside_shutdown
  action:
    - service: automation.trigger
      entity_id: automation.office_power_down
    - service: automation.trigger
      entity_id: automation.outside_power_down
    - data:
        transition: 60
      service: light.turn_off
      entity_id: [light.master_bed_michael, light.master_bed_catherine, light.hall_lamp, light.matt_lamp, light.aj_lamp, light.jacqui_lamp]

